[program:ingestion-scheduler]
process_name=%(program_name)s
command=php /home/ploi/ingestion.kraite.com/artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=waygou
numprocs=1
redirect_stderr=true
stdout_logfile=/home/ploi/ingestion.kraite.com/storage/logs/scheduler.log
stopwaitsecs=60
