[program:ingestion-scheduler]
process_name=%(program_name)s
command=php /home/martingalian/ingestion.martingalian.com/artisan schedule:work
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=martingalian
numprocs=1
redirect_stderr=true
stdout_logfile=/home/martingalian/ingestion.martingalian.com/storage/logs/scheduler.log
stopwaitsecs=60
